[package]
name = "un-pak"
authors = ["spuds"]
repository = "https://github.com/bananaturtlesandwich/un-pak"
description = "a no-nonsense unreal pak parsing crate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "*"
strum = { version = "*", features = ["derive"] }
hashbrown = "*"
thiserror = "*"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
