[package]
name = "repak"
repository.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true

[features]
default = ["compression", "encryption"]
compression = ["dep:flate2", "dep:zstd"]
oodle = []
oodle_loader = ["dep:oodle_loader"]
encryption = ["dep:aes"]

[dependencies]
byteorder = "1.4"
aes = { workspace = true, optional = true }
flate2 = { version = "1.0", optional = true }
zstd = { version = "0.12", optional = true }
oodle_loader = { path = "../oodle_loader", optional = true}
thiserror = "1.0"
sha1 = { workspace = true }
strum = { workspace = true }

[dev-dependencies]
base64 = { workspace = true }
paste = "1.0.11"
